# Dockerfile for creating a Docker image for a FastAPI backend application in development.

# This Dockerfile sets up an environment for running a FastAPI backend application
# in a development environment. It installs Python dependencies using Poetry, 
# optionally installs JupyterLab for development purposes, exposes port 8000 for 
# the FastAPI server, and includes useful development tools.

# Use an official Python runtime as a parent image

FROM python:3.11-slim

LABEL maintainer="elias.niederwieser@fraunhofer.it"
LABEL version="0.1.0"
LABEL description="Development Docker Image for FastAPI Backend"


ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    wget \
    git \
    vim \
    htop \
    iputils-ping \
    net-tools \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir "poetry==1.5.1" 

WORKDIR /app

COPY . /app

RUN poetry config virtualenvs.create false && \
poetry install

ARG INSTALL_JUPYTER=false
RUN bash -c "if [ $INSTALL_JUPYTER == 'true' ] ; then pip install jupyterlab ; fi"

EXPOSE 8000
USER root
