"""Description of migrn

Revision ID: 30f19fba881b
Revises: a8293b35ec14
Create Date: 2024-09-18 12:44:12.867512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f19fba881b'
down_revision: Union[str, None] = 'a8293b35ec14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_active')
    # ### end Alembic commands ###
