version: '3'
services:
  vue-app:
    container_name: chek-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "83:80"
    networks:
      - default
    restart: always

networks:
  default:
    external: true
    name: scoobydoo